using ExamPracticeSystemFull.Forms;
using ExamPracticeSystemFull.Models;
using ExamPracticeSystemFull.Services;

namespace ExamPracticeSystemFull.Forms
{
    using System;
    using System.Drawing; // For Color
    using System.Windows.Forms;
    using ExamPracticeSystemFull.Models; // For User and UserSession
    using ExamPracticeSystemFull.Services; // For UserService and ValidationService

    public partial class LoginForm : Form
    {
        private readonly UserService _userService; // Service for user authentication

        /// <summary>
        /// Constructor for the LoginForm.
        /// Initializes the UserService and sets up the form.
        /// </summary>
        public LoginForm()
        {
            InitializeComponent(); // This method is generated by the WinForms designer
            _userService = new UserService(); // Instantiate the UserService
            SetupFormDefaults(); // Custom setup for the form
        }

        /// <summary>
        /// Sets up default properties for form controls and labels.
        /// </summary>
        private void SetupFormDefaults()
        {
            // Set form title
            this.Text = "Login - Exam Management System";
            this.StartPosition = FormStartPosition.CenterScreen; // Center the form on screen

            // Example of how you might initialize UI components if not using designer fully:
            // Ensure these controls are added in your Form1.Designer.cs or manually if creating dynamically.
            // For this example, we assume controls named txtUsername, txtPassword, btnLogin, btnRegister, lblErrorMessage exist.

            // Clear any previous error messages
            lblErrorMessage.Text = "";
            lblErrorMessage.ForeColor = Color.Red; // Set error message color
            lblErrorMessage.Visible = false; // Hide error message initially

            txtPassword.UseSystemPasswordChar = true; // Hide password characters
        }

        /// <summary>
        /// Event handler for the Login button click.
        /// Authenticates the user based on provided username and password.
        /// </summary>
        private void btnLogin_Click(object sender, EventArgs e)
        {
            string username = txtUsername.Text.Trim();
            string password = txtPassword.Text;

            // Validate inputs before attempting authentication
            if (string.IsNullOrEmpty(username) || string.IsNullOrEmpty(password))
            {
                ShowErrorMessage("Username and password cannot be empty.");
                return;
            }

            try
            {
                User authenticatedUser = _userService.AuthenticateUser(username, password);

                if (authenticatedUser != null)
                {
                    // Login successful
                    UserSession.Instance.Login(authenticatedUser); // Set current user in session
                    ShowInfoMessage($"Login successful. Welcome, {authenticatedUser.Username}!");

                    // Open the MainForm and hide the LoginForm
                    MainForm mainForm = new MainForm();
                    mainForm.FormClosed += (s, args) => this.Close(); // Ensure app closes when main form closes
                    mainForm.Show();
                    this.Hide();
                }
                else
                {
                    // Login failed
                    ShowErrorMessage("Invalid username or password.");
                }
            }
            catch (Exception ex)
            {
                ShowErrorMessage($"An error occurred during login: {ex.Message}");
                // Log the exception for debugging purposes
                Console.WriteLine($"Login Error: {ex.Message}");
            }
        }

        /// <summary>
        /// Event handler for the Register button click.
        /// Opens the RegistrationForm.
        /// </summary>
        private void btnRegister_Click(object sender, EventArgs e)
        {
            // Open the RegistrationForm
            RegistrationForm registrationForm = new RegistrationForm();
            registrationForm.ShowDialog(); // Show as dialog, so user must close it before interacting with LoginForm again
        }

        /// <summary>
        /// Displays an error message to the user.
        /// </summary>
        /// <param name="message">The error message to display.</param>
        private void ShowErrorMessage(string message)
        {
            lblErrorMessage.Text = message;
            lblErrorMessage.ForeColor = Color.Red;
            lblErrorMessage.Visible = true;
        }

        /// <summary>
        /// Displays an informational message to the user.
        /// </summary>
        /// <param name="message">The informational message to display.</param>
        private void ShowInfoMessage(string message)
        {
            lblErrorMessage.Text = message;
            lblErrorMessage.ForeColor = Color.Green; // Green for success/info messages
            lblErrorMessage.Visible = true;
        }


        // --- Designer-generated code (typically in LoginForm.Designer.cs) ---
        // For the purpose of this response, assume these are properly defined in your designer file.
        // You will need to ensure these controls are added to your form in Visual Studio Designer.

        private System.Windows.Forms.Label lblUsername;
        private System.Windows.Forms.TextBox txtUsername;
        private System.Windows.Forms.Label lblPassword;
        private System.Windows.Forms.TextBox txtPassword;
        private System.Windows.Forms.Button btnLogin;
        private System.Windows.Forms.Button btnRegister;
        private System.Windows.Forms.Label lblErrorMessage;
        private System.Windows.Forms.Label lblTitle; // Add a title label

        private void InitializeComponent()
        {
            this.lblUsername = new System.Windows.Forms.Label();
            this.txtUsername = new System.Windows.Forms.TextBox();
            this.lblPassword = new System.Windows.Forms.Label();
            this.txtPassword = new System.Windows.Forms.TextBox();
            this.btnLogin = new System.Windows.Forms.Button();
            this.btnRegister = new System.Windows.Forms.Button();
            this.lblErrorMessage = new System.Windows.Forms.Label();
            this.lblTitle = new System.Windows.Forms.Label();
            this.SuspendLayout();
            // 
            // lblUsername
            // 
            this.lblUsername.AutoSize = true;
            this.lblUsername.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.lblUsername.Location = new System.Drawing.Point(50, 100);
            this.lblUsername.Name = "lblUsername";
            this.lblUsername.Size = new System.Drawing.Size(71, 19);
            this.lblUsername.TabIndex = 0;
            this.lblUsername.Text = "Username:";
            // 
            // txtUsername
            // 
            this.txtUsername.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.txtUsername.Location = new System.Drawing.Point(150, 97);
            this.txtUsername.Name = "txtUsername";
            this.txtUsername.Size = new System.Drawing.Size(200, 25);
            this.txtUsername.TabIndex = 1;
            // 
            // lblPassword
            // 
            this.lblPassword.AutoSize = true;
            this.lblPassword.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.lblPassword.Location = new System.Drawing.Point(50, 140);
            this.lblPassword.Name = "lblPassword";
            this.lblPassword.Size = new System.Drawing.Size(69, 19);
            this.lblPassword.TabIndex = 2;
            this.lblPassword.Text = "Password:";
            // 
            // txtPassword
            // 
            this.txtPassword.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.txtPassword.Location = new System.Drawing.Point(150, 137);
            this.txtPassword.Name = "txtPassword";
            this.txtPassword.Size = new System.Drawing.Size(200, 25);
            this.txtPassword.TabIndex = 3;
            this.txtPassword.UseSystemPasswordChar = true;
            // 
            // btnLogin
            // 
            this.btnLogin.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.btnLogin.Location = new System.Drawing.Point(150, 190);
            this.btnLogin.Name = "btnLogin";
            this.btnLogin.Size = new System.Drawing.Size(90, 35);
            this.btnLogin.TabIndex = 4;
            this.btnLogin.Text = "Login";
            this.btnLogin.UseVisualStyleBackColor = true;
            this.btnLogin.Click += new System.EventHandler(this.btnLogin_Click);
            // 
            // btnRegister
            // 
            this.btnRegister.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.btnRegister.Location = new System.Drawing.Point(260, 190);
            this.btnRegister.Name = "btnRegister";
            this.btnRegister.Size = new System.Drawing.Size(90, 35);
            this.btnRegister.TabIndex = 5;
            this.btnRegister.Text = "Register";
            this.btnRegister.UseVisualStyleBackColor = true;
            this.btnRegister.Click += new System.EventHandler(this.btnRegister_Click);
            // 
            // lblErrorMessage
            // 
            this.lblErrorMessage.AutoSize = true;
            this.lblErrorMessage.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Point);
            this.lblErrorMessage.ForeColor = System.Drawing.Color.Red;
            this.lblErrorMessage.Location = new System.Drawing.Point(50, 240);
            this.lblErrorMessage.MaximumSize = new System.Drawing.Size(300, 0); // Allow wrapping
            this.lblErrorMessage.Name = "lblErrorMessage";
            this.lblErrorMessage.Size = new System.Drawing.Size(76, 15);
            this.lblErrorMessage.TabIndex = 6;
            this.lblErrorMessage.Text = "Error Message";
            this.lblErrorMessage.Visible = false;
            // 
            // lblTitle
            // 
            this.lblTitle.AutoSize = true;
            this.lblTitle.Font = new System.Drawing.Font("Segoe UI", 16F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.lblTitle.Location = new System.Drawing.Point(50, 30);
            this.lblTitle.Name = "lblTitle";
            this.lblTitle.Size = new System.Drawing.Size(306, 30);
            this.lblTitle.TabIndex = 7;
            this.lblTitle.Text = "Exam Management System";
            // 
            // LoginForm
            // 
            this.ClientSize = new System.Drawing.Size(400, 300);
            this.Controls.Add(this.lblTitle);
            this.Controls.Add(this.lblErrorMessage);
            this.Controls.Add(this.btnRegister);
            this.Controls.Add(this.btnLogin);
            this.Controls.Add(this.txtPassword);
            this.Controls.Add(this.lblPassword);
            this.Controls.Add(this.txtUsername);
            this.Controls.Add(this.lblUsername);
            this.Name = "LoginForm";
            this.Text = "Login";
            this.Load += new System.EventHandler(this.LoginForm_Load); // Add Load event handler
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        private void LoginForm_Load(object sender, EventArgs e)
        {
            // Any specific logic on form load can go here.
            // For example, focusing the username textbox.
            txtUsername.Focus();
        }
    }
}
