using ExamPracticeSystemFull.Models; // For User and UserRole
using ExamPracticeSystemFull.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ExamPracticeSystemFull.Models; // For User and UserRole
using ExamPracticeSystemFull.Services; // For UserService and ValidationService
namespace ExamPracticeSystemFull.Forms
{
    using System;
    using System.Drawing; // For Color
    using System.Windows.Forms;
    using ExamPracticeSystemFull.Models; // For User and UserRole
    using ExamPracticeSystemFull.Services; // For UserService and ValidationService

    public partial class RegistrationForm : Form
    {
        private readonly UserService _userService; // Service for user registration
        // private readonly ValidationService _validationService; // Service for input validation

        /// <summary>
        /// Constructor for the RegistrationForm.
        /// Initializes services and sets up the form.
        /// </summary>
        public RegistrationForm()
        {
            InitializeComponent(); // This method is generated by the WinForms designer
            _userService = new UserService(); // Instantiate the UserService
            // ValidationService is static, so no instantiation needed, but good to have a reference if it were instance-based.
            // _validationService = new ValidationService(); 
            SetupFormDefaults(); // Custom setup for the form
        }

        /// <summary>
        /// Sets up default properties for form controls and labels.
        /// Populates the role combo box.
        /// </summary>
        private void SetupFormDefaults()
        {
            this.Text = "Register - Exam Management System";
            this.StartPosition = FormStartPosition.CenterParent; // Center relative to parent form (LoginForm)

            lblErrorMessage.Text = "";
            lblErrorMessage.ForeColor = Color.Red;
            lblErrorMessage.Visible = false;

            txtPassword.UseSystemPasswordChar = true; // Hide password characters
            txtConfirmPassword.UseSystemPasswordChar = true; // Hide password characters

            // Populate the ComboBox for UserRole
            cmbRole.DataSource = Enum.GetValues(typeof(UserRole));
            cmbRole.SelectedItem = UserRole.Student; // Default to Student role
        }

        /// <summary>
        /// Event handler for the Register button click.
        /// Validates user input and attempts to register a new user.
        /// </summary>
        private void btnRegister_Click(object sender, EventArgs e)
        {
            string username = txtUsername.Text.Trim();
            string password = txtPassword.Text;
            string confirmPassword = txtConfirmPassword.Text;
            string email = txtEmail.Text.Trim();
            string idNumber = txtIDNumber.Text.Trim();
            UserRole role = (UserRole)cmbRole.SelectedItem;

            // Perform all validations using ValidationService
            ValidationResult usernameValidation = ValidationService.ValidateUsername(username);
            if (!usernameValidation.IsValid) { ShowErrorMessage(usernameValidation.Message); return; }

            ValidationResult passwordValidation = ValidationService.ValidatePassword(password);
            if (!passwordValidation.IsValid) { ShowErrorMessage(passwordValidation.Message); return; }

            if (password != confirmPassword)
            {
                ShowErrorMessage("Password and Confirm Password do not match.");
                return;
            }

            ValidationResult emailValidation = ValidationService.ValidateEmail(email);
            if (!emailValidation.IsValid) { ShowErrorMessage(emailValidation.Message); return; }

            ValidationResult idNumberValidation = ValidationService.ValidateIDNumber(idNumber);
            if (!idNumberValidation.IsValid) { ShowErrorMessage(idNumberValidation.Message); return; }

            try
            {
                // Create a new User object
                User newUser = new User(username, password, role, email, idNumber);

                // Attempt to register the user
                bool success = _userService.RegisterUser(newUser);

                if (success)
                {
                    ShowInfoMessage($"Registration successful for {username}! You can now login.");
                    // Optionally clear fields or close form after successful registration
                    ClearFormFields();
                    this.Close(); // Close registration form after successful registration
                }
                else
                {
                    ShowErrorMessage("Registration failed. Username might already exist.");
                }
            }
            catch (Exception ex)
            {
                ShowErrorMessage($"An error occurred during registration: {ex.Message}");
                Console.WriteLine($"Registration Error: {ex.Message}");
            }
        }

        /// <summary>
        /// Clears all input fields on the form.
        /// </summary>
        private void ClearFormFields()
        {
            txtUsername.Clear();
            txtPassword.Clear();
            txtConfirmPassword.Clear();
            txtEmail.Clear();
            txtIDNumber.Clear();
            cmbRole.SelectedItem = UserRole.Student;
            lblErrorMessage.Text = "";
            lblErrorMessage.Visible = false;
        }

        /// <summary>
        /// Displays an error message to the user.
        /// </summary>
        /// <param name="message">The error message to display.</param>
        private void ShowErrorMessage(string message)
        {
            lblErrorMessage.Text = message;
            lblErrorMessage.ForeColor = Color.Red;
            lblErrorMessage.Visible = true;
        }

        /// <summary>
        /// Displays an informational message to the user.
        /// </summary>
        /// <param name="message">The informational message to display.</param>
        private void ShowInfoMessage(string message)
        {
            lblErrorMessage.Text = message;
            lblErrorMessage.ForeColor = Color.Green;
            lblErrorMessage.Visible = true;
        }

        // --- Designer-generated code (typically in RegistrationForm.Designer.cs) ---
        // For the purpose of this response, assume these are properly defined in your designer file.
        // You will need to ensure these controls are added to your form in Visual Studio Designer.

        private System.Windows.Forms.Label lblTitle;
        private System.Windows.Forms.Label lblUsername;
        private System.Windows.Forms.TextBox txtUsername;
        private System.Windows.Forms.Label lblPassword;
        private System.Windows.Forms.TextBox txtPassword;
        private System.Windows.Forms.Label lblConfirmPassword;
        private System.Windows.Forms.TextBox txtConfirmPassword;
        private System.Windows.Forms.Label lblEmail;
        private System.Windows.Forms.TextBox txtEmail;
        private System.Windows.Forms.Label lblIDNumber;
        private System.Windows.Forms.TextBox txtIDNumber;
        private System.Windows.Forms.Label lblRole;
        private System.Windows.Forms.ComboBox cmbRole;
        private System.Windows.Forms.Button btnRegister;
        private System.Windows.Forms.Label lblErrorMessage;

        private void InitializeComponent()
        {
            this.lblTitle = new System.Windows.Forms.Label();
            this.lblUsername = new System.Windows.Forms.Label();
            this.txtUsername = new System.Windows.Forms.TextBox();
            this.lblPassword = new System.Windows.Forms.Label();
            this.txtPassword = new System.Windows.Forms.TextBox();
            this.lblConfirmPassword = new System.Windows.Forms.Label();
            this.txtConfirmPassword = new System.Windows.Forms.TextBox();
            this.lblEmail = new System.Windows.Forms.Label();
            this.txtEmail = new System.Windows.Forms.TextBox();
            this.lblIDNumber = new System.Windows.Forms.Label();
            this.txtIDNumber = new System.Windows.Forms.TextBox();
            this.lblRole = new System.Windows.Forms.Label();
            this.cmbRole = new System.Windows.Forms.ComboBox();
            this.btnRegister = new System.Windows.Forms.Button();
            this.lblErrorMessage = new System.Windows.Forms.Label();
            this.SuspendLayout();
            // 
            // lblTitle
            // 
            this.lblTitle.AutoSize = true;
            this.lblTitle.Font = new System.Drawing.Font("Segoe UI", 16F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.lblTitle.Location = new System.Drawing.Point(50, 30);
            this.lblTitle.Name = "lblTitle";
            this.lblTitle.Size = new System.Drawing.Size(213, 30);
            this.lblTitle.TabIndex = 0;
            this.lblTitle.Text = "New User Register";
            // 
            // lblUsername
            // 
            this.lblUsername.AutoSize = true;
            this.lblUsername.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.lblUsername.Location = new System.Drawing.Point(50, 90);
            this.lblUsername.Name = "lblUsername";
            this.lblUsername.Size = new System.Drawing.Size(71, 19);
            this.lblUsername.TabIndex = 1;
            this.lblUsername.Text = "Username:";
            // 
            // txtUsername
            // 
            this.txtUsername.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.txtUsername.Location = new System.Drawing.Point(200, 87);
            this.txtUsername.Name = "txtUsername";
            this.txtUsername.Size = new System.Drawing.Size(200, 25);
            this.txtUsername.TabIndex = 2;
            // 
            // lblPassword
            // 
            this.lblPassword.AutoSize = true;
            this.lblPassword.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.lblPassword.Location = new System.Drawing.Point(50, 130);
            this.lblPassword.Name = "lblPassword";
            this.lblPassword.Size = new System.Drawing.Size(69, 19);
            this.lblPassword.TabIndex = 3;
            this.lblPassword.Text = "Password:";
            // 
            // txtPassword
            // 
            this.txtPassword.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.txtPassword.Location = new System.Drawing.Point(200, 127);
            this.txtPassword.Name = "txtPassword";
            this.txtPassword.Size = new System.Drawing.Size(200, 25);
            this.txtPassword.TabIndex = 4;
            this.txtPassword.UseSystemPasswordChar = true;
            // 
            // lblConfirmPassword
            // 
            this.lblConfirmPassword.AutoSize = true;
            this.lblConfirmPassword.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.lblConfirmPassword.Location = new System.Drawing.Point(50, 170);
            this.lblConfirmPassword.Name = "lblConfirmPassword";
            this.lblConfirmPassword.Size = new System.Drawing.Size(124, 19);
            this.lblConfirmPassword.TabIndex = 5;
            this.lblConfirmPassword.Text = "Confirm Password:";
            // 
            // txtConfirmPassword
            // 
            this.txtConfirmPassword.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.txtConfirmPassword.Location = new System.Drawing.Point(200, 167);
            this.txtConfirmPassword.Name = "txtConfirmPassword";
            this.txtConfirmPassword.Size = new System.Drawing.Size(200, 25);
            this.txtConfirmPassword.TabIndex = 6;
            this.txtConfirmPassword.UseSystemPasswordChar = true;
            // 
            // lblEmail
            // 
            this.lblEmail.AutoSize = true;
            this.lblEmail.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.lblEmail.Location = new System.Drawing.Point(50, 210);
            this.lblEmail.Name = "lblEmail";
            this.lblEmail.Size = new System.Drawing.Size(44, 19);
            this.lblEmail.TabIndex = 7;
            this.lblEmail.Text = "Email:";
            // 
            // txtEmail
            // 
            this.txtEmail.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.txtEmail.Location = new System.Drawing.Point(200, 207);
            this.txtEmail.Name = "txtEmail";
            this.txtEmail.Size = new System.Drawing.Size(200, 25);
            this.txtEmail.TabIndex = 8;
            // 
            // lblIDNumber
            // 
            this.lblIDNumber.AutoSize = true;
            this.lblIDNumber.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.lblIDNumber.Location = new System.Drawing.Point(50, 250);
            this.lblIDNumber.Name = "lblIDNumber";
            this.lblIDNumber.Size = new System.Drawing.Size(78, 19);
            this.lblIDNumber.TabIndex = 9;
            this.lblIDNumber.Text = "ID Number:";
            // 
            // txtIDNumber
            // 
            this.txtIDNumber.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.txtIDNumber.Location = new System.Drawing.Point(200, 247);
            this.txtIDNumber.Name = "txtIDNumber";
            this.txtIDNumber.Size = new System.Drawing.Size(200, 25);
            this.txtIDNumber.TabIndex = 10;
            // 
            // lblRole
            // 
            this.lblRole.AutoSize = true;
            this.lblRole.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.lblRole.Location = new System.Drawing.Point(50, 290);
            this.lblRole.Name = "lblRole";
            this.lblRole.Size = new System.Drawing.Size(39, 19);
            this.lblRole.TabIndex = 11;
            this.lblRole.Text = "Role:";
            // 
            // cmbRole
            // 
            this.cmbRole.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbRole.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            this.cmbRole.FormattingEnabled = true;
            this.cmbRole.Location = new System.Drawing.Point(200, 287);
            this.cmbRole.Name = "cmbRole";
            this.cmbRole.Size = new System.Drawing.Size(200, 25);
            this.cmbRole.TabIndex = 12;
            // 
            // btnRegister
            // 
            this.btnRegister.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            this.btnRegister.Location = new System.Drawing.Point(200, 340);
            this.btnRegister.Name = "btnRegister";
            this.btnRegister.Size = new System.Drawing.Size(90, 35);
            this.btnRegister.TabIndex = 13;
            this.btnRegister.Text = "Register";
            this.btnRegister.UseVisualStyleBackColor = true;
            this.btnRegister.Click += new System.EventHandler(this.btnRegister_Click);
            // 
            // lblErrorMessage
            // 
            this.lblErrorMessage.AutoSize = true;
            this.lblErrorMessage.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Point);
            this.lblErrorMessage.ForeColor = System.Drawing.Color.Red;
            this.lblErrorMessage.Location = new System.Drawing.Point(50, 390);
            this.lblErrorMessage.MaximumSize = new System.Drawing.Size(350, 0); // Allow wrapping
            this.lblErrorMessage.Name = "lblErrorMessage";
            this.lblErrorMessage.Size = new System.Drawing.Size(76, 15);
            this.lblErrorMessage.TabIndex = 14;
            this.lblErrorMessage.Text = "Error Message";
            this.lblErrorMessage.Visible = false;
            // 
            // RegistrationForm
            // 
            this.ClientSize = new System.Drawing.Size(450, 450);
            this.Controls.Add(this.lblErrorMessage);
            this.Controls.Add(this.btnRegister);
            this.Controls.Add(this.cmbRole);
            this.Controls.Add(this.lblRole);
            this.Controls.Add(this.txtIDNumber);
            this.Controls.Add(this.lblIDNumber);
            this.Controls.Add(this.txtEmail);
            this.Controls.Add(this.lblEmail);
            this.Controls.Add(this.txtConfirmPassword);
            this.Controls.Add(this.lblConfirmPassword);
            this.Controls.Add(this.txtPassword);
            this.Controls.Add(this.lblPassword);
            this.Controls.Add(this.txtUsername);
            this.Controls.Add(this.lblUsername);
            this.Controls.Add(this.lblTitle);
            this.Name = "RegistrationForm";
            this.Text = "Register";
            this.Load += new System.EventHandler(this.RegistrationForm_Load); // Add Load event handler
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        private void RegistrationForm_Load(object sender, EventArgs e)
        {
            txtUsername.Focus(); // Set initial focus
        }
    }
}
